version: '3.9'

networks:
  backend:
    name: ${NETWORK_PREFIX}-rosbank-backend

services:
  search:
      container_name: search_user
#      image: nikolos123/signing:0.0.1
      env_file: .env
      ports:
        - 8052:8052
      build: .
      privileged: true
#      command: uvicorn app.main:application --host 0.0.0.0 --port 8098 --reload
      networks:
        - backend
